### ISSUE TITLE
Error with the newest Sponge

### ISSUE THREAD

**Issue by pianwan** [euOnmyoji/NewHonor-plugin-for-sponge#7]
Hello,
I have an error when players join the game.

Sponge Version: spongeforge-1.12.2-2838-7.1.7-RC3830
FML Version: forge-1.12.2-14.23.5.2838

```
[12:36:49] [Server thread/WARN] [newhonor]: init player scoreboard error
java.lang.NullPointerException: null
        at net.minecraft.scoreboard.ScorePlayerTeam.func_186682_a(SourceFile:148) ~[bhh.class:?]
        at net.minecraft.scoreboard.ScorePlayerTeam.setCollisionRule(SourceFile:678) ~[bhh.class:?]
        at org.spongepowered.common.scoreboard.builder.SpongeTeamBuilder.build(SpongeTeamBuilder.java:181) ~[SpongeTeamBuilder.class:1.12.2-2838-7.1.7-RC3831]
        at com.github.euonmyoji.newhonor.manager.ScoreBoardManager.lambda$execute$1(ScoreBoardManager.java:77) ~[ScoreBoardManager.class:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_101]
        at java.util.stream.DistinctOps$1$2.accept(Unknown Source) ~[?:1.8.0_101]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_101]
        at java.util.Collections$2.tryAdvance(Unknown Source) ~[?:1.8.0_101]
        at java.util.Collections$2.forEachRemaining(Unknown Source) ~[?:1.8.0_101]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_101]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_101]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_101]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_101]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_101]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_101]
        at com.github.euonmyoji.newhonor.manager.ScoreBoardManager.execute(ScoreBoardManager.java:58) ~[ScoreBoardManager.class:?]
        at com.github.euonmyoji.newhonor.manager.ScoreBoardManager.refresh(ScoreBoardManager.java:99) ~[ScoreBoardManager.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.1.7-RC3831]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3831]
        at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2838-7.1.7-RC3831]
        at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:183) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3831]
        at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:169) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3831]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) [?:1.8.0_101]
        at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2838-7.1.7-RC3831]
        at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2838-7.1.7-RC3831]
        at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.12.2-2838-7.1.7-RC3831]
        at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:417) [SpongeMod.class:1.12.2-2838-7.1.7-RC3831]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_172_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:1252) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:1202) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by KunoSayo** [comment]
I tried to fix it in newhonor-b400 version
I added a lot def values to team

**Comment by dnstzzx** [comment]
> I tried to fix it in newhonor-b400 version
> I added a lot def values to team


This problem still exists in b400 version

forge-1.12.2-14.23.5.2838
spongeforge-1.12.2-2838-7.1.7-RC3840
↓

[11:49:33] [Server thread/WARN] [newhonor]: init player scoreboard error
java.lang.NullPointerException: null
	at net.minecraft.scoreboard.ScorePlayerTeam.func_186682_a(SourceFile:148) ~[bhh.class:?]
	at net.minecraft.scoreboard.ScorePlayerTeam.setCollisionRule(SourceFile:678) ~[bhh.class:?]
	at org.spongepowered.common.scoreboard.builder.SpongeTeamBuilder.build(SpongeTeamBuilder.java:181) ~[SpongeTeamBuilder.class:1.12.2-2838-7.1.7-RC3840]
	at com.github.euonmyoji.newhonor.manager.ScoreBoardManager.lambda$execute$1(ScoreBoardManager.java:83) ~[ScoreBoardManager.class:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_202]
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175) ~[?:1.8.0_202]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_202]
	at java.util.Collections$2.tryAdvance(Collections.java:4717) ~[?:1.8.0_202]
	at java.util.Collections$2.forEachRemaining(Collections.java:4725) ~[?:1.8.0_202]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_202]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_202]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_202]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_202]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_202]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_202]
	at com.github.euonmyoji.newhonor.manager.ScoreBoardManager.execute(ScoreBoardManager.java:58) ~[ScoreBoardManager.class:?]
	at com.github.euonmyoji.newhonor.manager.ScoreBoardManager.refresh(ScoreBoardManager.java:105) ~[ScoreBoardManager.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.1.7-RC3840]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3840]
	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2838-7.1.7-RC3840]
	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:183) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3840]
	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:169) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3840]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_202]
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2838-7.1.7-RC3840]
	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2838-7.1.7-RC3840]
	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.12.2-2838-7.1.7-RC3840]
	at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:417) [SpongeMod.class:1.12.2-2838-7.1.7-RC3840]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:752) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:702) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

**Comment by KunoSayo** [comment]
Maybe it's sponge's bug?
(Wait for checking

**Comment by KunoSayo** [comment]
stable is ok
